name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^9.1.1
  
  #dateFormat
  intl: ^0.20.2

  #Database
  floor: any

  #make request to api
  retrofit: ^4.9.1

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # Image picker for selecting images
  image_picker: ^1.0.4 # New dependency

  #Hooks
  flutter_hooks: ^0.21.3+1

  #chached image 
  cached_network_image: ^3.2.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^8.2.1
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "ic_launcher_new"
  ios: "true"
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
